# Generated by Django 3.2.20 on 2023-11-20 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braco', models.CharField(max_length=100)),
                ('perna', models.CharField(max_length=100)),
                ('peito', models.CharField(max_length=100)),
                ('costa', models.CharField(max_length=100)),
                ('gluteo', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.clientes')),
            ],
        ),
    ]
