# Generated by Django 3.2.20 on 2023-11-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20231120_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='braco',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='costa',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='gluteo',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='peito',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='perna',
            field=models.TextField(default=False),
        ),
    ]
