# Generated by Django 3.2.20 on 2023-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20231121_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='braco',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='costa',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='gluteo',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='peito',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='perna',
            field=models.TextField(default=0, null=True),
        ),
    ]
