# Generated by Django 3.2.20 on 2023-11-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20231124_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='braco',
            field=models.CharField(choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='costa',
            field=models.CharField(choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='gluteo',
            field=models.CharField(choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='peito',
            field=models.CharField(choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='perna',
            field=models.CharField(choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default=0, max_length=100, null=True),
        ),
    ]
