# Generated by Django 3.2.20 on 2023-11-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20231124_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='braco',
            field=models.CharField(blank=True, choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='costa',
            field=models.CharField(blank=True, choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='gluteo',
            field=models.CharField(blank=True, choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='peito',
            field=models.CharField(blank=True, choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='perna',
            field=models.CharField(blank=True, choices=[('3 séries, 8 repetições', '3 séries, 8 repetições'), ('3 séries, 12 repetições', '3 séries, 12 repetições'), ('3 séries, 15 repetições', '3 séries, 15 repetições'), ('4 séries, 8 repetições', '4 séries, 8 repetições'), ('4 séries, 12 repetições', '4 séries, 12 repetições'), ('4 séries, 15 repetições', '4 séries, 15 repetições')], default='', max_length=100),
        ),
    ]
